# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cold Case Act
author: Joshua A. Fayer
description: > # this means to ignore newlines until "baseurl:"
  A bill created by an AP US Government and Politics class to establish an independent review board to facilitate the release of cold case documents.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://coldcaseact.com" # the base hostname & protocol for your site

collections:
  sections:
    output: false
  emails:
    output: true

defaults:
  -
    scope:
      type: sections
    values:
      layout: section
  -
    scope:
      type: emails
    values:
      layout: email

# Build settings
markdown: kramdown
sass:
  style: compressed
